name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  lint:
    name: Run golangci-lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23' # adjust to your Go version

      - name: Download Go modules
        run: |
          go mod download
          go mod verify

      - name: Debug modules
        run: |
          echo "=== Go version ==="
          go version
          echo "=== Module list ==="
          go list -m all
          echo "=== Build test ==="
          go build ./internal/interface/routes/

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --config ./golangci/golangci.toml ./...

  test:
    name: Run Go Tests
    runs-on: ubuntu-latest
    needs: lint  # run tests only if lint passes

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Download Go modules
        run: |
          go mod download
          go mod verify

      - name: Run unit tests
        run: go test ./... -v -race -coverprofile=coverage.out -covermode=atomic

      - name: Upload coverage to GitHub (optional)
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.out

